add calc
MIIIG/elixir-course-24 pull request #1
Opened 2024-02-10 19:20 UTC by MIIIG

week 1 homework - calculator, tests,  docs, dialyxir

2024-02-11 06:12 UTC, am-kantox approved these changes
Все хорошо, но попробуйте немного думать про завтрашний день; всегда, даже когда выполняете дурацкую простую домашку :)

Что будет если аргументом передана строка, или, там, список? Что будет, если вторым параметром в `div/2` будет передан ноль? Вы заметили, и правильно отреагировали на то, что `Kernel.//2` возвращает флоат — пойдите немного дальше. Но это все придирки, да, в целом все отлично.

2024-02-11 06:12 UTC, am-kantox commented on calc/README.md
> +Documentation can be generated with [ExDoc](https://github.com/elixir-lang/ex_doc)
Привыкайте прямо сразу подчищать документацию.

2024-02-11 06:12 UTC, am-kantox commented on calc/lib/calc.ex
> +  @spec add(integer(), integer()) :: integer()
Функция отлично отработает для двух флоатов, а по спеке — это не так.
```suggestion
  @spec add(integer() | float(), integer() | float()) :: integer() | float()
```

2024-02-11 06:12 UTC, am-kantox commented on calc/lib/calc.ex
> +  @spec div(integer(), integer()) :: float()
❤

2024-02-11 19:07 UTC, MIIIG commented on calc/README.md
> +Documentation can be generated with [ExDoc](https://github.com/elixir-lang/ex_doc)
убрал

2024-02-11 19:13 UTC, MIIIG commented on calc/lib/calc.ex
> +  @spec add(integer(), integer()) :: integer()
добавил типы, тесты и функцию на все остальные типы аргументов сматчил

2024-02-18 11:20 UTC, am-kantox requested changes

2024-02-18 11:20 UTC, am-kantox commented on calc/lib/calc.ex
> +  def sub(x, y) when number(x) and number(y) do
Я сомневаюсь, что это компилируется.

2024-02-18 19:40 UTC, MIIIG commented on calc/lib/calc.ex
> +  def sub(x, y) when number(x) and number(y) do
Спасибо, исправил тесты и опечатку на проверку

2024-02-18 20:59 UTC, am-kantox approved these changes
:zap: :droplet: :zap: :gem: :zap: :blue_heart: :zap:

Ну, makefile — это лишняя зависимость, а лучше он не делает :)

2024-02-20 16:17 UTC, merged